### ISSUE TITLE
Time on tickets

### ISSUE THREAD

**Issue by Colovorat** [nfreader/banbus#9]
https://atlantaned.space/banbus/ticket/0c2555a926b10fd7 for me showing that it happened 12 hours ago, but it's not. I'm just living in UTC +12

**Comment by nfreader** [comment]
This is an issue with the timestamp library. The entire thing is a mess and in serious need of an overhaul.

**Comment by nfreader** [comment]
Fixed (several versions ago I'm just now catching up on issues)
